name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout sources
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and load
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: exceedxo/currency-converter:latest
    -
      name: Tests
      run: cargo test --verbose
    
